Update : creation of the github action with YARN
inarix/glowing-winner pull request #1
Opened 2021-03-18 10:03 UTC by saisona

2021-03-23 15:16 UTC, cesumilo requested changes
Please explain how you can use glowing-winner in github action. Better doc, less questions

2021-04-12 08:42 UTC, cesumilo requested changes
Missing information about secrets in the README.md

2021-04-12 21:01 UTC, saisona commented
Those secrets are defaults (given by GitHub itself) one so nothing to do. That's the reason why I didn't explained. Only thing to do is to copy paste 😇😀

2021-04-30 12:47 UTC, cesumilo approved these changes

2021-04-30 13:00 UTC, merged